name: licensify
description: A lightweight yet powerful license management solution for Flutter and Dart applications with cryptographically secure signatures
version: 1.7.1
homepage: https://github.com/nogipx/licensify
repository: https://github.com/nogipx/licensify
issue_tracker: https://github.com/nogipx/licensify/issues
documentation: https://github.com/nogipx/licensify/blob/main/README.md

environment:
  sdk: ^3.7.0

dependencies:
  uuid: ^4.5.1
  pointycastle: ^4.0.0
  basic_utils: ^5.8.2
  crypto: ^3.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - license
  - security
  - validation
  - cryptography
  - web

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
