name: licensify
description: A modern Dart library for secure license generation and validation using PASETO v4.
version: 1.0.0
homepage: https://github.com/nogipx/licensify
repository: https://github.com/nogipx/licensify
issue_tracker: https://github.com/nogipx/licensify/issues
documentation: https://github.com/nogipx/licensify/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  paseto_dart: ^1.0.0
  pointycastle: ^3.9.1
  uuid: ^4.5.1
  args: ^2.4.2
  crypto: ^3.0.3
  asn1lib: ^1.6.1
  cryptography: ^2.7.0

dev_dependencies:
  test: ^1.21.0
  lints: ^4.0.0

executables:
  licensify: licensify

topics:
  - license
  - digital-signature 
  - cryptography 
  - software-licensing 
  - ecdsa 

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
