name: licensify
description: A modern Dart library for secure license generation and validation using PASETO v4.
version: 4.1.0
homepage: https://github.com/nogipx/licensify
repository: https://github.com/nogipx/licensify
issue_tracker: https://github.com/nogipx/licensify/issues
documentation: https://github.com/nogipx/licensify/blob/main/README.md
funding:
  - https://liberapay.com/nogipx

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  paseto_dart: ^2.0.0
  uuid: ^4.5.1
  args: ^2.4.2
  meta: ^1.9.1

dev_dependencies:
  test: ^1.21.0
  lints: ^4.0.0

executables:
  licensify: licensify

topics:
  - license
  - digital-signature
  - cryptography
  - software-licensing 
  - paseto
