name: licensify
description: Secure license management for Dart/Flutter with ECDSA signatures, configurable encryption, and cross-platform support.
version: 2.3.0
homepage: https://github.com/nogipx/licensify
repository: https://github.com/nogipx/licensify
issue_tracker: https://github.com/nogipx/licensify/issues
documentation: https://github.com/nogipx/licensify/blob/main/README.md

environment:
  sdk: ^3.7.0

dependencies:
  uuid: ^4.5.1
  pointycastle: ^4.0.0
  crypto: ^3.0.3
  args: ^2.4.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  licensify: licensify

topics:
  - license
  - digital-signature 
  - cryptography 
  - software-licensing 
  - ecdsa 

# Platform support
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
